### ISSUE TITLE
Some subdomains may be unavailable

### ISSUE THREAD

**Issue by rylat** [ChameleonLinux/status.cos.ovh#1]
There might a downtime of around 24 hours.

We are moving our DNS zone to CloudFlare. Since we used DNSSEC we need up to 24 hours to safely apply new DNS management.

**Comment by Py64** [comment]
Changing "possible problems" flag to "major outage". See #2

**Comment by Py64** [comment]
Because this issue is DNS-related only, I remove another labels.

**Comment by Py64** [comment]
It should be safe now.
