### ISSUE TITLE
Server reinstallation

### ISSUE THREAD

**Issue by rylat** [ChameleonLinux/status.cos.ovh#17]
Server will be reinstalled. Before the 1.0 setup has been running stable, the NGINX was reconfigured multiple times, same with VSFTPD, Postfix, Dovecot (and before: exim).

Expected downtime: up to 47 1/2 hours (26.06 19:30 - 28.06).
Starting: 19.00 UTC+01 26.06.2016 (if rain will not interrupt).

**Comment by Py64** [comment]
Base system installed.

**Comment by Py64** [comment]
Booted successfuly.

**Comment by Py64** [comment]
Got problems with LXC bridge.

**Comment by Py64** [comment]
main os: ubuntu
os in containers: archlinux

**Comment by Py64** [comment]
due to problems with creating archlinux container, the containers will have ubuntu.

soon reverse will be ready

**Comment by Py64** [comment]
Uploading backup. MySQL server waits for database recovery.

The reverse server will be configured now.

**Comment by Py64** [comment]
**introducing shared APT cache**

**Comment by Py64** [comment]
reverse server responds currently only for direct-IP requests

**Comment by Py64** [comment]
php available for kitee666.cos.ovh

**Comment by Py64** [comment]
50% of backup

**Comment by Py64** [comment]
simple 502 page on reverse

**Comment by Py64** [comment]
started ghost for cos.ovh in container and configured reverse for it

**Comment by Py64** [comment]
todo:

- mysql (install backup)
- kitee666.cos.ovh (install backup, point to new database)
- forums.cos.ovh (install discourse)
- #18
- #19
- add ssl to reverse (currently cloudflare will keep serving offline cache)

**Comment by Py64** [comment]
todo:

- forums.cos.ovh (install discourse)
- #18
- #19 
- put github pages behind reverse
