### ISSUE TITLE
Discourse setup

### ISSUE THREAD

**Issue by rylat** [ChameleonLinux/status.cos.ovh#23]

**Comment by Py64** [comment]
DISCONNECTING ALL CONTAINERS!

**Comment by Py64** [comment]
network is alive. for an hour...

**Comment by Py64** [comment]
Reverse alive again. Now final Discourse installation.

**Comment by Py64** [comment]
blank page, js errors.

**Comment by Py64** [comment]
Cloudflare caching disabled for Discourse.

see additional steps: #24

**Comment by Py64** [comment]
password length requirement - to lower.

**Comment by Py64** [comment]
routing problems - mail server IS NOT accessible from local network (but IS accessible from outside) - ALL docker containers should use 10.0.3.15 (if running inside LXC network). ALL LXC containers can use mail.cos.ovh.

**Comment by Py64** [comment]
applying new hosts rules to containers.
rebuilding docker

**Comment by Py64** [comment]
finally decided to use vanilla - discourse has problems with connecting to mail server

**Comment by Py64** [comment]
#25
