### ISSUE TITLE
Read-only mode. Backup

### ISSUE THREAD

**Issue by rylat** [ChameleonLinux/status.cos.ovh#8]
20.06.2016 - read-only mode.

**Comment by Py64** [comment]
Ok, soon whole database should be read-only.

**Comment by Py64** [comment]
Switched back to **scheduled maintenance* - fixing some problems with CloudFlare.

**Comment by Py64** [comment]
The read-only warning is being implemented. This may cause 500 errors to appear.

**Comment by Py64** [comment]
> Warning: read-only mode will be enabled soon. All POST requests will be rejected and the database will be locked. See status page for more details about this maintenance.

**Comment by Py64** [comment]
19:30 - scheduled lockdown.

**Comment by Py64** [comment]
19:35 UTC+01:00 - rescheduled.

**Comment by Py64** [comment]
19:40 UTC+01:00 - rescheduled. Sorry for this - read-only notification is just not completed.

**Comment by Py64** [comment]
FTP & Mails now rejected.

**Comment by Py64** [comment]
problems with db lock. rescheduled - 19:50

**Comment by Py64** [comment]
ending
